[tool.pytest.ini_options]
testpaths = "tests"
filterwarnings = "ignore::DeprecationWarning"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
ignore_missing_imports = true
